Learning tensorflow 

[Video 1: Beginner intro](https://www.youtube.com/watch?v=72s6hJwyfDg&list=PLnrz0kK2OBEeLJRiLoTnjwgb-31d8Wdx0&index=18)

In [58]:
import tensorflow as tf


In [59]:
mnist = tf.keras.datasets.mnist

(X_train, y_train), (X_test, y_test) = mnist.load_data()


In [60]:
X_train.shape

(60000, 28, 28)

In [61]:
y_train.shape

(60000,)

In [62]:
X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [63]:
X_train, X_test = X_train / 255.0, X_test / 255 # pre processing making numbers 0 - 1

In [64]:
X_train[0]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

In [65]:
from tensorflow.keras import models, layers, losses, optimizers

In [66]:
model = models.Sequential()
model.add(layers.InputLayer((28, 28)))
model.add(layers.Flatten())
model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dropout(0.2))
model.add(layers.Dense(10))

In [67]:
nonsense_pred = model(X_train[:1]).numpy()
tf.nn.softmax(nonsense_pred).numpy()

array([[0.04563341, 0.08919439, 0.15214446, 0.08386908, 0.10347278,
        0.17341165, 0.08703017, 0.08766316, 0.12838133, 0.04919953]],
      dtype=float32)

In [68]:
loss_fn = losses.SparseCategoricalCrossentropy(from_logits=True)

loss_fn(y_train[:1], nonsense_pred)

<tf.Tensor: shape=(), dtype=float32, numpy=1.7520869970321655>

In [69]:
optimizer = optimizers.Adam(learning_rate=0.01)
model.compile(optimizer=optimizer, loss=loss_fn, metrics=['accuracy'])

In [70]:
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9064 - loss: 0.3151 
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9317 - loss: 0.2446
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9376 - loss: 0.2251  
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9416 - loss: 0.2175 
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9435 - loss: 0.2144
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9476 - loss: 0.2015  
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9494 - loss: 0.2042 
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9512 - loss: 0.1927
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9532 - loss: 0.1859  
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9539 - loss: 0.1840 


In [73]:
model.evaluate(X_test, y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9637 - loss: 0.2094


[0.2093939483165741, 0.963699996471405]

# Regression Task

In [79]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [80]:
DATA_DIR = '/home/owner/ml/ObsidianVault/csvFiles'
df = pd.read_csv(f'{DATA_DIR}/housing.csv')

scaler = StandardScaler()

X, y = df.drop('MedHouseVal', axis=1), df['MedHouseVal']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [81]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_train_scaled

array([[-0.01455552,  0.58569803, -0.43239535, ...,  0.02232943,
        -0.72248426,  0.65492757],
       [-1.20247269, -0.68409299,  0.79717717, ..., -0.05241494,
         1.35462633,  0.06596078],
       [-0.21606734, -0.12855942, -0.27131801, ...,  0.15656164,
        -0.75055332,  0.91447226],
       ...,
       [-0.9849512 , -1.23962657, -0.18565366, ..., -0.1034793 ,
        -0.89089863,  1.28881555],
       [-0.68008518,  0.50633609, -0.24218015, ..., -0.03676568,
         1.08329206, -1.37151749],
       [ 0.36615958, -1.87452208,  0.24839888, ...,  0.02454032,
         0.94294675, -0.73762951]], shape=(16512, 8))

In [82]:
X_train_scaled.shape

(16512, 8)

In [85]:
model = models.Sequential()
model.add(layers.Input((8,)))
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(1))

In [86]:
model.compile(optimizer='adam', loss='mse', metrics=['mae', 'r2_score']) # mean absolute err

In [89]:
model.fit(X_train_scaled, y_train, epochs=10)

Epoch 1/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3160 - mae: 0.3939 - r2_score: 0.7617 
Epoch 2/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3374 - mae: 0.3919 - r2_score: 0.7455
Epoch 3/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3126 - mae: 0.3850 - r2_score: 0.7642
Epoch 4/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.2980 - mae: 0.3799 - r2_score: 0.7752
Epoch 5/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3017 - mae: 0.3775 - r2_score: 0.7725
Epoch 6/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.2927 - mae: 0.3746 - r2_score: 0.7793
Epoch 7/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.2894 - mae: 0.3723 - r2_score: 0.7817
Epoch 8/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.2907 - mae: 0.3706 - r2_score: 0.7807
Epoch 9/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.2827 - mae: 0.3675 - r2_score: 0.7868
Epoch 10/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.2805 - mae: 0.3670 - r2_score: 0.788

In [90]:
model.evaluate(X_test_scaled, y_test)

129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.2991 - mae: 0.3756 - r2_score: 0.7792


[0.29911303520202637, 0.3755667507648468, 0.7792001366615295]

In [91]:
df.MedHouseVal.describe()

count    20640.000000
mean         2.068558
std          1.153956
min          0.149990
25%          1.196000
50%          1.797000
75%          2.647250
max          5.000010
Name: MedHouseVal, dtype: float64