This is a follow along of a youtube tutorial by sentdex about [Nerual Networks](https://www.youtube.com/watch?v=Wo5dMEP_BbI&list=PLQVvvaa0QuDcjD5BAw2DxE6OF2tius3V3)

In [10]:
import numpy as np
import matplotlib

In [ ]:
inputs = [1, 2, 3, 2.5] # every unique input has a unique weight

weights1 = [0.2, 0.8, -0.5, 1.0] # every nueron has a unique weight set
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2 # every unique neruon has a unique bias
bias2 = 3 # every unique neruon has a unique bias
bias3 = 0.5 # every unique neruon has a unique bias

# tweaking the weights and bias changes the outputs
output = [inputs[0] * weights1[0] + inputs[1] * weights1[1] + inputs[2] * weights1[2] + inputs[3] * weights1[3] + bias1, # can be replaced with dot product
          inputs[0] * weights2[0] + inputs[1] * weights2[1] + inputs[2] * weights2[2] + inputs[3] * weights2[3] + bias2,
          inputs[0] * weights3[0] + inputs[1] * weights3[1] + inputs[2] * weights3[2] + inputs[3] * weights3[3] + bias3,] # output from neurons

print(output)



[4.8, 1.21, 2.385]


In [ ]:
inputs = [1, 2, 3, 2.5] 

weights = [[0.2, 0.8, -0.5, 1.0] ,
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87],]
biases = [2, 3, 0.5]


layer_outputs = []
for n_weights, n_bias in zip(weights, biases):
    n_output = 0
    for n_input, n_weight in zip(inputs, n_weights):
        n_output += n_input*n_weight
    n_output += n_bias
    layer_outputs.append(n_output)
    
print(layer_outputs)


[4.8, 1.21, 2.385]


In [24]:
inputs = [1, 2, 3, 2.5] 

weights = [[0.2, 0.8, -0.5, 1.0] ,
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87],]
biases = [2, 3, 0.5]

output = np.dot(weights, inputs) + biases
print(output)

[4.8   1.21  2.385]


In [ ]:
#1st layer
inputs = [[1, 2, 3, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1.0] ,
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87],]
biases = [2, 3, 0.5]

#2nd layer
weights2 = [[0.1, -0.14, 0.5] ,
           [-0.5, 0.12, -0.33],
           [-0.44, 0.73, -0.13],]
biases2 = [-1, 2, -0.5]

layer1_outputs = np.dot(inputs, np.array(weights).T) + biases # we use .T or transpose to swap the rows and colombs to fit the needed amounts for dot to work
layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2 # the inputs for the next layer is the outputs of the previous layer

print(layer2_outputs)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [36]:
np.random.seed(0)

X = [[1, 2, 3, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]]



class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons) # prevents need of transpose
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases
        
layer1 = Layer_Dense(4, 5) # neurons can be any number you want
layer2 = Layer_Dense(5, 2) # input must be same number as nuerons as previous layer

layer1.forward(X)
print(layer1.output)
print("----------")
layer2.forward(layer1.output)
print(layer2.output)

[[ 0.10758131  1.03983522  0.24462411  0.31821498  0.18851053]
 [-0.08349796  0.70846411  0.00293357  0.44701525  0.36360538]
 [-0.50763245  0.55688422  0.07987797 -0.34889573  0.04553042]]
----------
[[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]
