This is a follow along of a youtube tutorial by sentdex about [Nerual Networks](https://www.youtube.com/watch?v=Wo5dMEP_BbI&list=PLQVvvaa0QuDcjD5BAw2DxE6OF2tius3V3)

In [24]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data
import matplotlib.pyplot as plt
import math

In [3]:
inputs = [1, 2, 3, 2.5] # every unique input has a unique weight

weights1 = [0.2, 0.8, -0.5, 1.0] # every nueron has a unique weight set
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2 # every unique neruon has a unique bias
bias2 = 3 # every unique neruon has a unique bias
bias3 = 0.5 # every unique neruon has a unique bias

# tweaking the weights and bias changes the outputs
output = [inputs[0] * weights1[0] + inputs[1] * weights1[1] + inputs[2] * weights1[2] + inputs[3] * weights1[3] + bias1, # can be replaced with dot product
          inputs[0] * weights2[0] + inputs[1] * weights2[1] + inputs[2] * weights2[2] + inputs[3] * weights2[3] + bias2,
          inputs[0] * weights3[0] + inputs[1] * weights3[1] + inputs[2] * weights3[2] + inputs[3] * weights3[3] + bias3,] # output from neurons

print(output)



[4.8, 1.21, 2.385]


In [4]:
inputs = [1, 2, 3, 2.5] 

weights = [[0.2, 0.8, -0.5, 1.0] ,
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87],]
biases = [2, 3, 0.5]


layer_outputs = []
for n_weights, n_bias in zip(weights, biases):
    n_output = 0
    for n_input, n_weight in zip(inputs, n_weights):
        n_output += n_input*n_weight
    n_output += n_bias
    layer_outputs.append(n_output)
    
print(layer_outputs)


[4.8, 1.21, 2.385]


In [5]:
inputs = [1, 2, 3, 2.5] 

weights = [[0.2, 0.8, -0.5, 1.0] ,
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87],]
biases = [2, 3, 0.5]

output = np.dot(weights, inputs) + biases
print(output)

[4.8   1.21  2.385]


In [6]:
#1st layer
inputs = [[1, 2, 3, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1.0] ,
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87],]
biases = [2, 3, 0.5]

#2nd layer
weights2 = [[0.1, -0.14, 0.5] ,
           [-0.5, 0.12, -0.33],
           [-0.44, 0.73, -0.13],]
biases2 = [-1, 2, -0.5]

layer1_outputs = np.dot(inputs, np.array(weights).T) + biases # we use .T or transpose to swap the rows and colombs to fit the needed amounts for dot to work
layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2 # the inputs for the next layer is the outputs of the previous layer

print(layer2_outputs)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [49]:
### main class throughout videos

np.random.seed(0)

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons) # prevents need of transpose
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

# Rectified linear unit
class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

class Activation_Softmax:
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probalities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probalities

class Loss:
    def calc(self, output, y):
        sample_losses = self.forward(output, y)
        data_loss = np.mean(sample_losses)
        return data_loss

class Loss_CategoricalCrossentropy(Loss):
    def forward(self, y_pred, y_true):
        samples = len(y_pred)
        y_pred_clipped = np.clip(y_pred, 1e-7, 1-1e-7) # prevents inf values
        
        if len(y_true.shape) == 1: # scalar targets
            correct_confidences = y_pred_clipped[range(samples), y_true]
        elif len(y_true.shape) == 2: # 2d array targets one hot encoded
            correct_confidences = np.sum(y_pred_clipped * y_true, axis=1)
            
        negative_log_likely = -np.log(correct_confidences)
        return negative_log_likely

X, y = spiral_data(samples=100, classes=3)

dense1 = Layer_Dense(2, 3)
activation1 = Activation_ReLU()

dense2 = Layer_Dense(3, 3)
activation2 = Activation_Softmax()

dense1.forward(X)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)

loss_func = Loss_CategoricalCrossentropy()
loss = loss_func.calc(activation2.output, y)

print("Loss:", loss)

# video seris is over :(

Loss: 1.0984449588022467


In [ ]:
X = [[1, 2, 3, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]]

inputs = [0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100]
output = []

# rectified linear func
for i in inputs:
    output.append(max(0, i))

print(output)
    

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


In [ ]:
## softmax function

layer_outputs = [[4.8, 1.21, 2.385],
                 [8.9, -1.81, 0.2],
                 [1.41, 1.051, 0.026]]

exp_values = np.exp(layer_outputs)
norm_values = exp_values / np.sum(exp_values, axis=1, keepdims=True) # axis 1 sum all rows, keepdims keeps the shape so we can divide it
    
print(norm_values)

[[8.95282664e-01 2.47083068e-02 8.00090293e-02]
 [9.99811129e-01 2.23163963e-05 1.66554348e-04]
 [5.13097164e-01 3.58333899e-01 1.28568936e-01]]


In [ ]:
## Loss

softmax_output = [0.7, 0.1, 0.2]
target_output = [1, 0, 0] # target of index 0

loss = -(math.log(softmax_output[0]) * target_output[0] +
         math.log(softmax_output[1]) * target_output[1] +
         math.log(softmax_output[2]) * target_output[2] )

# same as
loss = -math.log(softmax_output[0])

print(-math.log(0.7))
print(-math.log(0.5))





0.35667494393873245
0.6931471805599453


In [44]:
softmax_outputs = np.array([[0.7, 0.1, 0.2],
                            [0.1, 0.5, 0.4],
                            [0.02, 0.9, 0.08]])
class_targets = [0, 1, 1]

print(softmax_outputs[[0, 1, 2], class_targets])

[0.7 0.5 0.9]
