Learning tensorflow 

[Video 1: Beginner intro](https://www.youtube.com/watch?v=72s6hJwyfDg&list=PLnrz0kK2OBEeLJRiLoTnjwgb-31d8Wdx0&index=18)

In [1]:
import tensorflow as tf


I0000 00:00:1783436032.925154    1135 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1783436032.929043    1135 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
I0000 00:00:1783436033.414283    1135 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
I0000 00:00:1783436035.230572    1135 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

In [2]:
mnist = tf.keras.datasets.mnist

(X_train, y_train), (X_test, y_test) = mnist.load_data()


In [3]:
X_train.shape

(60000, 28, 28)

In [4]:
y_train.shape

(60000,)

In [5]:
X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [6]:
X_train, X_test = X_train / 255.0, X_test / 255 # pre processing making numbers 0 - 1

In [7]:
X_train[0]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

In [8]:
from tensorflow.keras import models, layers, losses, optimizers

In [9]:
model = models.Sequential()
model.add(layers.InputLayer((28, 28)))
model.add(layers.Flatten())
model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dropout(0.2))
model.add(layers.Dense(10))

E0000 00:00:1783436037.345871    1135 cuda_executor.cc:1737] INTERNAL: CUDA Runtime error: Failed call to cudaGetRuntimeVersion: Error loading CUDA libraries. GPU will not be used.: Error loading CUDA libraries. GPU will not be used.
W0000 00:00:1783436037.370564    1135 gpu_device.cc:2365] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In [10]:
nonsense_pred = model(X_train[:1]).numpy()
tf.nn.softmax(nonsense_pred).numpy()

array([[0.10401922, 0.03940763, 0.08921503, 0.10257589, 0.098883  ,
        0.06353472, 0.10523636, 0.13773383, 0.10385373, 0.15554053]],
      dtype=float32)

In [11]:
loss_fn = losses.SparseCategoricalCrossentropy(from_logits=True)

loss_fn(y_train[:1], nonsense_pred)

<tf.Tensor: shape=(), dtype=float32, numpy=2.7561686038970947>

In [12]:
optimizer = optimizers.Adam(learning_rate=0.01)
model.compile(optimizer=optimizer, loss=loss_fn, metrics=['accuracy'])

In [13]:
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9066 - loss: 0.3157
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9330 - loss: 0.2394  
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 21s 11ms/step - accuracy: 0.9407 - loss: 0.2228
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ -14s -7636us/step - accuracy: 0.9429 - loss: 0.2127
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9469 - loss: 0.2054  
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9477 - loss: 0.2015
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9518 - loss: 0.1892   
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9525 - loss: 0.1872 
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9542 - loss: 0.1841
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9567 - loss: 0.1797   


In [14]:
model.evaluate(X_test, y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9669 - loss: 0.1748  


[0.1747879832983017, 0.9668999910354614]

# Regression Task

In [15]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [16]:
DATA_DIR = '/home/owner/ml/ObsidianVault/csvFiles'
df = pd.read_csv(f'{DATA_DIR}/housing.csv')

scaler = StandardScaler()

X, y = df.drop('MedHouseVal', axis=1), df['MedHouseVal']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [17]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_train_scaled

array([[-1.0340489 ,  1.37691086, -0.1700144 , ..., -0.08410519,
         1.74283895, -1.06073841],
       [-0.55262413, -1.08338905, -0.18844142, ..., -0.06530571,
        -1.16567659,  1.26800151],
       [-0.78252064, -1.16275357, -0.5699862 , ...,  0.09415541,
         0.40332937, -0.92581142],
       ...,
       [-0.20541093, -0.44847295,  3.07002749, ..., -0.04934895,
         2.15031214, -0.74091147],
       [ 0.43933088, -1.16275357, -0.06380369, ..., -0.10256311,
         1.06840056, -1.23564377],
       [ 2.76982253,  1.85309794,  0.78859331, ...,  0.01339469,
        -0.716051  ,  0.72329625]], shape=(16512, 8))

In [18]:
X_train_scaled.shape

(16512, 8)

In [19]:
model = models.Sequential()
model.add(layers.Input((8,)))
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(1))

In [20]:
model.compile(optimizer='adam', loss='mse', metrics=['mae', 'r2_score']) # mean absolute err

In [21]:
model.fit(X_train_scaled, y_train, epochs=10)

Epoch 1/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 1.0118 - mae: 0.5998 - r2_score: 0.2388
Epoch 2/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 18s 35ms/step - loss: 0.3839 - mae: 0.4419 - r2_score: 0.7112
Epoch 3/10
516/516 ━━━━━━━━━━━━━━━━━━━━ -17s -32756us/step - loss: 0.3701 - mae: 0.4271 - r2_score: 0.7216
Epoch 4/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3489 - mae: 0.4157 - r2_score: 0.7375
Epoch 5/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3606 - mae: 0.4107 - r2_score: 0.7287
Epoch 6/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3276 - mae: 0.3987 - r2_score: 0.7536  
Epoch 7/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3554 - mae: 0.3965 - r2_score: 0.7326  
Epoch 8/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.3426 - mae: 0.3874 - r2_score: 0.7422  
Epoch 9/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 991us/step - loss: 0.2963 - mae: 0.3784 - r2_score: 0.7771
Epoch 10/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 986us/step - loss: 0.2960 - mae: 0.3778

In [22]:
model.evaluate(X_test_scaled, y_test)

129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3436 - mae: 0.3891 - r2_score: 0.7437  


[0.3436357080936432, 0.3890603184700012, 0.7436667680740356]

In [23]:
df.MedHouseVal.describe()

count    20640.000000
mean         2.068558
std          1.153956
min          0.149990
25%          1.196000
50%          1.797000
75%          2.647250
max          5.000010
Name: MedHouseVal, dtype: float64

# Creating my own model

In [24]:
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras import models, layers, losses, optimizers

In [25]:
DATA_DIR = '/home/owner/ml/ObsidianVault/csvFiles'
housing_data = pd.read_csv(f'{DATA_DIR}/housing.csv')

print(housing_data.shape)
print(housing_data.head)


(20640, 9)
<bound method NDFrame.head of        MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

In [26]:
X = housing_data.drop('MedHouseVal', axis=1)
y = housing_data.MedHouseVal

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [28]:
Scalar = StandardScaler()

X_train_scaled = Scalar.fit_transform(X_train)
X_test_scaled = Scalar.transform(X_test)

In [29]:
X_train_scaled.shape

(16512, 8)

In [30]:
model = models.Sequential()
model.add(layers.Input((8,)))
model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(1))

In [31]:
model.compile(optimizer='adam', loss='mse', metrics=['mae', 'r2_score', 'accuracy']) # mean absolute err

In [32]:
model.fit(X_train_scaled, y_train, epochs=10)

Epoch 1/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0031 - loss: 0.6515 - mae: 0.5526 - r2_score: 0.5118
Epoch 2/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0030 - loss: 0.3722 - mae: 0.4322 - r2_score: 0.7210
Epoch 3/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0031 - loss: 0.3503 - mae: 0.4170 - r2_score: 0.7375
Epoch 4/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0031 - loss: 0.3645 - mae: 0.4064 - r2_score: 0.7269
Epoch 5/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0031 - loss: 0.3177 - mae: 0.3928 - r2_score: 0.7619
Epoch 6/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0031 - loss: 0.3060 - mae: 0.3861 - r2_score: 0.7707
Epoch 7/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0031 - loss: 0.2978 - mae: 0.3808 - r2_score: 0.7768
Epoch 8/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0031 - loss: 0.2944 - mae: 0.3770 - r2_score: 0.7794  
Epoch 9/10
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms

In [33]:
model.evaluate(X_test_scaled, y_test)

129/129 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0024 - loss: 0.3173 - mae: 0.3837 - r2_score: 0.7596     


[0.31726598739624023,
 0.3836939334869385,
 0.7595807313919067,
 0.002422480611130595]

```python
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras import models, layers, losses, optimizers

DATA_DIR = '/home/owner/ml/ObsidianVault/csvFiles'
housing_data = pd.read_csv(f'{DATA_DIR}/housing.csv')


X = housing_data.drop('MedHouseVal', axis=1)
y = housing_data.MedHouseVal

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

Scalar = StandardScaler()

X_train_scaled = Scalar.fit_transform(X_train)
X_test_scaled = Scalar.transform(X_test)

model = models.Sequential()
model.add(layers.Input((8,)))
model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(1))

model.compile(optimizer='adam', loss='mse', metrics=['mae', 'r2_score', 'accuracy']) # mean absolute err
model.fit(X_train, y_train, epochs=10)
model.evaluate(X_test, y_test)
```

# CIFAR-10 dataset

In [34]:
import tensorflow as tf
from tensorflow.keras import models, layers, datasets

In [36]:
(X_train, X_test), (y_train, y_test) = datasets.cifar10.load_data()

KeyboardInterrupt: 